# Tell Travis CI we're using PHP
language: php

# Versions of PHP to test against
php:
	- 5.3
	- 5.4
	- 5.5

before_script: 
	- git clone https://github.com/WordPress/WordPress.git wordpress
	- php WordPress/index.php
	- php functions.php

script: phpunit